version: '3'

services:
  product:
    build:
      context: .
      dockerfile: Dockerfile
    image: testprocompose
    ports:
    - "8080:9098"
#    volumes:
#  postgres:
#    image: postgres
#    environment:
#      -POSTGRESS_PASSWORD=mypass

